#!/bin/sh
set -e -x

erlc *.erl

mkdir -p stage/bin
mkdir -p stage/lib
mkdir -p stage/src

echo 'Celestial Dire Badger' > stage/team
echo 'Jed Davis <jld@ccs.neu.edu>' > stage/contact

cp wrapper stage/bin/run
chmod +x stage/bin/run
cp *.beam stage/lib/
cp *.erl README stage/src/
gcc -std=c99 -m32 -Wall -O3 -march=i686 -o stage/bin/newworld newworld.c -lm

cp package stage/bin/

mv stage icfp08
tar zcvf submission.tgz icfp08
mv icfp08 stage
